# GitHub Action for generating a contribution graph with Pac-Man eating your contributions.

name: Generate Pac-Man

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Generate Pac-Man/Snake style SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: KetanParmar02
          outputs: |
            dist/github-contribution-grid-pacman.svg
            dist/github-contribution-grid-pacman.gif

      # Push changes
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
